In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("/home/muhammad/Desktop/insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [5]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [6]:
from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping

# Define model with Input layer (preferred way)
model = keras.Sequential([
    keras.Input(shape=(2,)),   # Input layer instead of input_shape in Dense
    keras.layers.Dense(1, activation='sigmoid',
                       kernel_initializer='ones', bias_initializer='zeros')
])

# Compile
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Early stopping
early_stop = EarlyStopping(monitor='loss', patience=1, restore_best_weights=True)

# Train
history = model.fit(X_train_scaled, y_train,
                    epochs=00,
                    batch_size=32,
                    callbacks=[early_stop],
                    verbose=1)   # <- change to 1 to see progress


Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 421ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5000 - l

In [12]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Example data (replace with your real dataset)
# X_train shape: (num_samples, num_features)
# y_train shape: (num_samples,)
X_train = np.array([[0,1],[1,0],[1,1],[0,0]], dtype=float)  # sample features
y_train = np.array([1, 1, 0, 0], dtype=float)               # sample labels

# Normalize features (important!)
X_train = X_train / np.max(X_train)

# Model
model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')  # Binary classification
])

# Compile
model.compile(optimizer=Adam(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train
model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=1)

# Test predictions
predictions = model.predict(X_train)
print("Predictions:", predictions)


Epoch 1/100


/home/muhammad/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.1667 - loss: 0.6884      
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7333 - loss: 0.6864 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8333 - loss: 0.6645 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8333 - loss: 0.6699 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7333 - loss: 0.6735 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.6782 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.6760 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 1.0000 - loss: 0.6436 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.6654 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 0.6569 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 1.0000 - loss: 0.6451 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 1.0000 - loss: 0.65

In [13]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.1667 - loss: 0.7971


[0.7970786690711975, 0.1666666716337204]

In [14]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Example dataset (replace with your real data)
X = np.array([[0,0], [0,1], [1,0], [1,1]])  # input features
y = np.array([0, 1, 1, 0])                  # labels

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

# Scale features (important for neural networks)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Build model
model = Sequential([
    Dense(4, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(1, activation='sigmoid')
])

# Compile
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train
model.fit(X_train, y_train, epochs=100, verbose=1)

# Evaluate on test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f"\nTest Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")

# Make predictions
predictions = model.predict(X_test)
print("Predictions:", predictions)


Epoch 1/100


/home/muhammad/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 468ms/step - accuracy: 0.5000 - loss: 0.7227
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5000 - loss: 0.7211
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7195
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5000 - loss: 0.7179
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7163
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5000 - loss: 0.7148
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7132
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5000 - loss: 0.7116
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5000 - loss: 0.7101
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7085
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5000 - loss: 0.7070
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5000 - loss: 0.7054


In [13]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.1084


[0.108397476375103, 1.0]

In [11]:
from tensorflow.keras.callbacks import EarlyStopping

# Stop training once accuracy reaches 1.0
early_stop = EarlyStopping(monitor='accuracy', patience=10, verbose=1, mode='max', restore_best_weights=True)

model.fit(
    X_train_scaled,
    y_train,
    epochs=1500,
    batch_size=32,
    verbose=0,  # hides output for each epoch
    callbacks=[early_stop]
)


Epoch 11: early stopping
Restoring model weights from the end of the best epoch: 1.


In [12]:
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

predictions = model.predict(X_test_scaled)
print("Predictions (first 10):", predictions[:10])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.1084
Test Loss: 0.108397476375103
Test Accuracy: 1.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
Predictions (first 10): [[0.8425273 ]
 [0.00172149]
 [0.18884948]
 [0.04522993]
 [0.86936986]
 [0.9215119 ]]


In [14]:
predicted_classes = (predictions > 0.5).astype(int)
print(predicted_classes[:10])


[[1]
 [0]
 [0]
 [0]
 [1]
 [1]]


In [15]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 1.0000 - loss: 0.1084


[0.108397476375103, 1.0]

In [17]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


array([[0.8425273 ],
       [0.00172149],
       [0.18884948],
       [0.04522993],
       [0.86936986],
       [0.9215119 ]], dtype=float32)

In [18]:
X_test_scaled

age  affordibility
2   0.47            1.0
10  0.18            1.0
21  0.26            0.0
11  0.28            1.0
14  0.49            1.0
9   0.61            1.0

In [19]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [22]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))
sigmoid(18)


0.9999999847700205

In [31]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

# --- 1. Define data (example) ---
X = np.array([[0.2, 1], [0.5, 0], [0.9, 1], [0.1, 0]])
y = np.array([0, 1, 1, 0])

# --- 2. Define model ---
model = keras.Sequential([
    layers.Dense(1, activation='sigmoid', input_shape=(2,))
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# --- 3. Train ---
model.fit(X, y, epochs=100, verbose=0)

# --- 4. Get weights ---
weights, bias = model.layers[0].get_weights()
print("Weights:", weights)
print("Bias:", bias)

# --- 5. Prediction using model.predict ---
sample = np.array([[0.47, 1]])   # numpy 2D array
prediction = model.predict(sample)
print("Prediction (via Keras):", prediction)

# --- 6. Manual prediction using sigmoid ---
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def prediction_function(age, affordibility):
    weighted_sum = weights[0][0]*age + weights[1][0]*affordibility + bias[0]
    return sigmoid(weighted_sum)

print("Manual Prediction:", prediction_function(0.47, 1))


/home/muhammad/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Weights: [[-0.24661948]
 [-0.10248528]]
Bias: [0.08229893]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
Prediction (via Keras): [[0.46602803]]
Manual Prediction: 0.466028044947417


In [24]:
weights = model.get_weights()

# Example: first layer weights and bias
layer1_weights = weights[0]
layer1_bias = weights[1]

print("Layer 1 weights:\n", layer1_weights)
print("Layer 1 bias:\n", layer1_bias)


Layer 1 weights:
 [[-0.00582941 -0.6377838  -1.4715261  -0.13753563 -0.5049171  -0.33714178
  -1.7911999   0.26401725]
 [-0.2635427   0.13849977  0.44459453  0.6107294  -0.6353826  -0.75357103
   0.45114323  0.3693309 ]]
Layer 1 bias:
 [-0.00600354 -0.03516004  0.36718488 -0.01667845  0.5847759   0.6652139
  0.26430884 -0.04596962]


In [25]:
predictions = model.predict(X_test_scaled)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step


In [29]:
import pandas as pd

sample = pd.DataFrame([[0.47, 1]], columns=['age', 'affordibility'])
prediction = model.predict(sample)
print("Prediction:", prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step
Prediction: [[0.8425273]]


In [36]:
coef, intercept

(array([[-0.24661948],
        [-0.10248528]], dtype=float32),
 array([0.08229893], dtype=float32))

In [28]:
import numpy as np

sample = np.array([[0.47, 1]])  # scaled values
prediction = model.predict(sample)
print("Prediction:", prediction)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step
Prediction: [[0.8425273]]


In [33]:
# Get weights from first (and only) Dense layer
weights, bias = model.layers[0].get_weights()

print("Weights:", weights)   # coefficients (as a 2D numpy array)
print("Bias:", bias)         # intercept (as a numpy array with 1 value)


Weights: [[-0.24661948]
 [-0.10248528]]
Bias: [0.08229893]


In [35]:
coef, intercept = model.get_weights()

In [37]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [38]:
X_test

age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [39]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(.47, 1)

/tmp/ipykernel_308306/396317115.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.46602804832178163

In [40]:
prediction_function(.18, 1)

/tmp/ipykernel_308306/396317115.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.483861144472697

In [41]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [42]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [43]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias 

In [44]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:0.7113403233723417
Epoch:1, w1:0.9556229728273669, w2:0.9058873696677865, bias:-0.2122349122718517, loss:0.6812647787377568
Epoch:2, w1:0.9416488476693794, w2:0.8719790823960313, bias:-0.2977578997796538, loss:0.6591474252715025
Epoch:3, w1:0.9323916996249162, w2:0.8457541517722915, bias:-0.3715094724003511, loss:0.6431523291301917
Epoch:4, w1:0.9272267472726993, w2:0.8262362885332687, bias:-0.43506643026891584, loss:0.6316873063379158
Epoch:5, w1:0.9255469396815343, w2:0.8124402814952774, bias:-0.48994490058938817, loss:0.623471707997592
Epoch:6, w1:0.9267936114129968, w2:0.8034375029757677, bias:-0.5375299543522853, loss:0.6175321183044205
Epoch:7, w1:0.93047170420295, w2:0.7983920007454487, bias:-0.5790424270894963, loss:0.6131591858705934
Epoch:8, w1:0.9361540784567942, w2:0.7965748796787705, bias:-0.6155315088627655, loss:0.6098518179750948
Epoch:9, w1:0.9434791243557357, w2:0.7973647616854131, bi

(5.051047623653049, 1.4569794548473887, -2.959653454625004)

In [45]:
coef, intercept

(array([[-0.24661948],
        [-0.10248528]], dtype=float32),
 array([0.08229893], dtype=float32))